FROM node:22.18

ARG CONFIGURAMA_FOLDER_PATH
ARG CONFIGURAMA_FOLDER_ENVIRONMENT
ARG CONFIGURAMA_FOLDER_BASE_URL

ENV CONFIGURAMA_FOLDER_PATH=$CONFIGURAMA_FOLDER_PATH
ENV CONFIGURAMA_FOLDER_ENVIRONMENT=$CONFIGURAMA_FOLDER_ENVIRONMENT
ENV CONFIGURAMA_FOLDER_BASE_URL=$CONFIGURAMA_FOLDER_BASE_URL

WORKDIR /across-relayer

COPY . ./

RUN apt-get update
RUN apt-get install -y libudev-dev libusb-1.0-0-dev jq yarn rsync
RUN yarn

RUN yarn build

ENTRYPOINT ["/bin/bash", "scripts/runCommand.sh"]
