FROM node:22.18

ARG CONFIGURAMA_BASE_URL
ARG CONFIGURAMA_ENV
ARG CONFIGURAMA_FILE_PATH
ARG RELAYER_EXTERNAL_INVENTORY_CONFIG

# We need to have these environment variables set for run-time as well
ENV CONFIGURAMA_BASE_URL=${CONFIGURAMA_BASE_URL}
ENV CONFIGURAMA_ENV=${CONFIGURAMA_ENV}
ENV CONFIGURAMA_FILE_PATH=${CONFIGURAMA_FILE_PATH}
ENV RELAYER_EXTERNAL_INVENTORY_CONFIG=${RELAYER_EXTERNAL_INVENTORY_CONFIG}

WORKDIR /across-relayer

COPY . ./

RUN apt-get update
RUN apt-get install -y libudev-dev libusb-1.0-0-dev jq yarn rsync
RUN yarn

RUN yarn build

ENTRYPOINT ["/bin/bash", "scripts/runCommand.sh"]
