name: Deploy
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Curl build and deploy webhook for GCP for UMA protocol repo
        run: ${{ secrets.PROTOCOL_BUILD_DEPLOY_WEBHOOK }}
        shell: bash
      - name: Curl build and deploy webhook for GCP for UMA across repo
        run: ${{ secrets.ACROSS_BUILD_DEPLOY_WEBHOOK }}
        shell: bash
